name: cddenv
channels:
 - anaconda
 - conda-forge
dependencies:
 - matplotlib=3.2.2
 - matplotlib-inline=0.1.2
 - notebook=6.4.0
 - numpy=1.19.5
 - pandas=1.1.5
 - pillow=8.3.0
 - scikit-learn=0.24.2
 - seaborn=0.11.1
